AllCops:
  Include:
    - 'app/**/*.rb'
    - 'frontend/**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/config.ru'
  Exclude:
    - 'app/**/*.slim'
    - 'app/**/*.erb'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'vendor/ruby/**/*'

Layout/EndOfLine:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false